# -*- coding: utf-8 -*-
"""Tic-tac-toe

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BYg5z-TX4Sv9RNVlp5Qt7W9SIpk9OdKp
"""

board = [' '] * 9

def print_board():
    for i in range(3):
        print(board[3*i] + ' | ' + board[3*i+1] + ' | ' + board[3*i+2])
        if i < 2:
            print('--+---+--')

def check(player):
    win = [
        [0,1,2], [3,4,5], [6,7,8],    # rows
        [0,3,6], [1,4,7], [2,5,8],    # columns
        [0,4,8], [2,4,6]              # diagonals
    ]
    for pos in win:
        if board[pos[0]] == board[pos[1]] == board[pos[2]] == player:
            return True
    return False

def play():
    p = 'X'
    moves = 0

    while True:
        print_board()
        pos = int(input(f"Player {p} turn (1-9): ")) - 1

        if pos < 0 or pos > 8 or board[pos] != ' ':
            print("Invalid move bro try again\n")
            continue

        board[pos] = p
        moves += 1

        if check(p):
            print_board()
            print(f"{p} wins 🎉")
            break

        if moves == 9:
            print_board()
            print("Draw match 🤝")
            break

        p = 'O' if p == 'X' else 'X'

play()